org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
# 沙盒/低配机器构建参数（1.9GB 内存也能编）
org.gradle.jvmargs=-Xmx980m -XX:MaxMetaspaceSize=380m -XX:ReservedCodeCacheSize=200m -XX:+UseSerialGC
org.gradle.workers.max=1
kotlin.incremental=false
org.gradle.daemon=false
kotlin.compiler.execution.strategy="in-process"
org.gradle.vfs.watch=false
